// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0vD6XEIeQhGBLEi6IR-HuWOW72r5PqX0',
    appId: '1:454030573780:web:9cc59ed4dca7b1718dfb41',
    messagingSenderId: '454030573780',
    projectId: 'task1-1e960',
    authDomain: 'task1-1e960.firebaseapp.com',
    storageBucket: 'task1-1e960.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRiq1wU7_GQeMH6Im7q0x13mAF71gzg6I',
    appId: '1:454030573780:android:0185a4015f1057b38dfb41',
    messagingSenderId: '454030573780',
    projectId: 'task1-1e960',
    storageBucket: 'task1-1e960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtB1FWbczi_LGs8NHQt5x6E2DcTUkXmc4',
    appId: '1:454030573780:ios:171c341c78c9685c8dfb41',
    messagingSenderId: '454030573780',
    projectId: 'task1-1e960',
    storageBucket: 'task1-1e960.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtB1FWbczi_LGs8NHQt5x6E2DcTUkXmc4',
    appId: '1:454030573780:ios:171c341c78c9685c8dfb41',
    messagingSenderId: '454030573780',
    projectId: 'task1-1e960',
    storageBucket: 'task1-1e960.appspot.com',
    iosBundleId: 'com.example.task1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0vD6XEIeQhGBLEi6IR-HuWOW72r5PqX0',
    appId: '1:454030573780:web:756c1f88be36a7168dfb41',
    messagingSenderId: '454030573780',
    projectId: 'task1-1e960',
    authDomain: 'task1-1e960.firebaseapp.com',
    storageBucket: 'task1-1e960.appspot.com',
  );

}